
# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ujjwal-tf-bucket"
    dynamodb_table = "tfstate-table"
    encrypt        = true
    key            = "components/vpc/terraform.tfstate"
    region         = "ap-south-1"
  }
}
