apiVersion: v1
kind: Pod
metadata:
  name: kaniko-eks
  namespace: ujjwal-agent
spec:
  serviceAccountName: service-account2
  automountServiceAccountToken: true
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.6.0-debug
    imagePullPolicy: Always
    args: ["--dockerfile=Dockerfile",
            "--context=git://github.com/carlossg/kaniko-demo.git",
            "--destination=458516813260.dkr.ecr.ap-south-1.amazonaws.com/ujjwal-ecr-repo:latest",
            "--destination=singhujjwal.jfrog.io/default-docker-local/ujjwal-artifactory:latest",
            "--cache=true"]
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  volumes:
    - name: docker-config
      configMap:
        name: ujjwal
